Repository openfed/kiso, pull requests merged in 2021-05, with the labels that each got.

#36 Bugfix/#30: Redefines the default `multiple` flag to know if it returns more than 1 item
  templates/field/field.html.twig
Labels: bug

#39 Bugfix/#29: Improved the "Branding" text to be used as both `<a title>` and `<img alt>` attributes value
  templates/block/branding/block--system-branding-block.html.twig
Labels: invalid

#38 Bugfix/#31: Fix strip tags, providing some allowed tags to be skipped
  includes/preprocess.layout.inc
  includes/preprocess.page.inc
  includes/preprocess.utils.inc
Labels: bug

#43 Bugfix/#32: Fix the `<ol>` numbering render for nested lists when mixed
  css/components/field/text-formatted.css
  scss/components/field/text-formatted.scss
Labels: invalid

#42 Feature/#41: New `core_version_requirement` key for Drupal 9 compatibility
  kiso.info.yml
Labels: enhancement
